import React from 'react';
import a1 from './priv.jpg';
import a2 from './des.jpg';
import './term.css';


const Privacy = () => {
return (
 <div style={{
		height: 'auto', backgroundColor: '#ffffff',}} className="privacy">
	   <img src={a1} alt="c" style={{ width: '100%',height: '100vh',}} />
       <div className="inner" style={{height: '213vh',}}>
                    <h1>Privacy Policy</h1>
                    <img src={a2} alt="a2" style={{ position: 'absolute',paddingTop: '110px', width: '300px', height: '60px', left:"480px", }} />
                    <p style={{paddingTop: '150px',}}> <b>Enviropromise Pvt Ltd </b> values your privacy. In this Privacy Policy ("Policy"), we describe how we collect, use, and disclose information, including Personal Information that we obtain about visitors to our websites and the services available through our Website ("Services."). “Personal Information" means any unique information or set of information that could be used to identify or contact an individual, such as the individual's name, title, mailing address, email address, phone number, employer/profession, login information, password, payment card information or other specific types of personal information.</p> 
                    <h2 style={{paddingTop: '390px',}}>1. Types of Information and Collection Methods </h2>
                    <p style={{paddingTop: '430px',}}><b>Information Submitted by You</b></p>
                    <p style={{paddingTop: '470px',}}>You may be asked to provide Personal Information anytime you are in contact with Enviropromise pvt ltd may collect Personal Information about you (and through third parties or other sources where permitted by law) when you interact with us, such as creating or registering for an account, using our products and services, downloading our software, requesting information, requesting notifications for service bulletin or products and services updates, participating in surveys, submitting a job application or when you otherwise actively send us data and Personal Information. In each such instance, you will know what data we collected because you voluntarily submitted it. You are not required to provide any Personal Information that we have requested, but if you chose not to do so, you may not be able to access certain content on our Website or products and services offered or we will not be able to respond to any inquiries you may have or process your orders.</p>
                    <p style={{paddingTop: '800px',}}>Examples include forwarding reference or marketing material to a friend or sending job referrals. Information Collected Through Third-Party Sources We may also collect information about you through our trusted third-party sources to assist us in providing product and service offerings to you. Information Automatically Collected Like many other websites, Microsemi uses automatic data collection tools, such as cookies, embedded web links, web beacons, gifs and other similar technologies. These tools automatically collect certain standard information that your browser sends to our Website when you visit our Website or use our Services, such as your domain name, your browser type, operating system, web pages you view, links you click, your IP address, the length of time you visit our Website or use our Services, the referring URL or the webpage that led you to our Website. Please see the section “Cookies and Similar Technologies” below for more information. Combination We and the third parties we engaged to provide services on our behalf may combine the information we collect from you over time and across our Website with Personal Information that you actively submit, to the extent permitted by applicable law.</p>
        </div> 
        <div className="p2" style={{ height: '100vh',}} >
                    <h2 style={{paddingTop: '0px',}}>2. How We May Use Your Information </h2>
                    <p style={{paddingTop: '40px',}}>We may use your information for purposes of operating our business and other legitimate purposes permitted by applicable law. We may use your personal information in the following ways: </p>
                    <p style={{paddingTop: '120px',}}><b> * </b>To communicate with you about our products or services, respond to your inquiries, fulfill and process your <b style={{ color: '#ffffff',}}>k.</b>request for our products and services, including helping you to complete transactions, process payments, <b style={{ color: '#ffffff',}}>k.</b>and other customer service purposes.</p>
                    <p style={{paddingTop: '220px',}}><b> * </b>To enable you to use certain features of our product and services.</p>
                    <p style={{paddingTop: '260px',}}><b> * </b>To administer the careers portion of the Website and process your application.</p>
                    <p style={{paddingTop: '300px',}}><b> * </b>To better understand how visitors use our Website and products and services, both on an aggregated and <b style={{ color: '#ffffff',}}>k.</b>individualized basis, in order to improve our Website and products and services and for other research and <b style={{ color: '#ffffff',}}>k.</b>analytical purposes.</p>
                    <p style={{paddingTop: '400px',}}><b> * </b>To send communications to you, either from Microsemi directly or from our partners, including for<b style={{ color: '#ffffff',}}>kkkkk k</b> marketing, newsletters, promotions, customer satisfaction surveys purposes and other communications <b style={{ color: '#ffffff',}}>k.</b>related to our business, including information about our solutions we think may interest you. You can edit <b style={{ color: '#ffffff',}}>k.</b>your communication preferences for receiving marketing emails as further explained below.</p>
        </div>  
        <div className="p3" style={{ height: '145vh',}} >
                    <h2 style={{paddingTop: '0px',}}>3. How We Share Your Information </h2>
                    <p style={{paddingTop: '40px',}}>We are not in the business of selling or sharing your Personal Information with third parties for marketing purposes unless you have granted us permission to do so. We may share and use your Personal Information as described below:</p>
                    <p style={{paddingTop: '150px',}}><b> * </b>With our affiliates and subsidiaries worldwide.</p>
                    <p style={{paddingTop: '190px',}}><b> * </b>With third-party vendors, service providers, contractors or agents as required to perform specific purposes <b style={{ color: '#ffffff',}}>k.</b>on our behalf. Examples are not limited to delivering packages, processing credit card payments, checking <b style={{ color: '#ffffff',}}>k.</b>for export compliance, and providing customer service.</p>
                    <p style={{paddingTop: '285px',}}><b> * </b>To geographically or sectorally relevant resellers and/or distributors, particularly if you or your company <b style={{ color: '#ffffff',}}>k.</b>have purchased through a third party before. These companies and persons often provide service to <b style={{ color: '#ffffff',}}>k.</b>Microsemi’s customers. They have access to customer information to perform their jobs, which is not <b style={{ color: '#ffffff',}}>k.</b>limited to marketing Microsemi products, but may not use it for other purposes.</p>
                    <p style={{paddingTop: '415px',}}><b> * </b>To comply with the law, a judicial proceeding, court order or a subpoena other legal processes, such as <b style={{ color: '#ffffff',}}>k.</b>requests from public and governmental authorities or law enforcement, or to exercise our legal rights or <b style={{ color: '#ffffff',}}>k.</b>defend against legal claims.</p>
                    <p style={{paddingTop: '515px',}}><b> * </b>Where we believe it is necessary to investigate, prevent, or take action regarding illegal activities, suspected <b style={{ color: '#ffffff',}}>k.</b>fraud, brand protection, situations involving potential threats to the safety of any person, violations of our <b style={{ color: '#ffffff',}}>k.</b>Terms of Use or this Policy, or as otherwise required by law.</p>
                    <p style={{paddingTop: '615px',}}><b> * </b>In connection with a prospective or actual sale, merger, transfer or other reorganization of all or parts of our <b style={{ color: '#ffffff',}}>k.</b>business.</p>
                    <p style={{paddingTop: '700px',}}>If you do not wish us to share your information as described below, you may choose not to supply any Personal Information to us when entering information into your account profile on our Website or by not placing orders for our products and services.</p>
        </div> 
        <div className="p4" style={{ height: '160vh',}} >
                   <h2 style={{paddingTop: '0px',}}>4. We May Use Cookies and Similar Technologies to Collect Information </h2>
                   < p style={{paddingTop: '60px',}}>We and our third-party service providers use cookies and other common web tracking mechanisms to track information about your use of our Website and Services. We may use this information, which is collected and remains in aggregate form, to understand how visitors use our Website so that we can better tailor our interactions with you when you browse our Website and to improve our Website.</p>
                   < p style={{paddingTop: '200px',}}> <b>Cookies</b></p>
                   < p style={{paddingTop: '230px',}}>A cookie is a small data file that our website stores on your computer hard drive for record-keeping purposes. We use cookies for website administration, such as maintaining your log-in or your preferences, to keep track of your navigation through our Website and to observe your navigation across other sites in order to better match your interests to Microsemi’s products and services. Most web browsers automatically accept cookies. If you prefer not to receive cookies, you can set your browser to allow you to refuse the setting of all or some cookies. Although you may still use our Website without the cookie, some areas or features of our Website or Services may not function for you.</p>
                   < p style={{paddingTop: '460px',}}><b>Third-Party Analytics</b></p>
                   < p style={{paddingTop: '490px',}}>We also use automated devices and applications, such as Google Analytics to collect information in an anonymous form about how visitors use our Website. For information on Google’s privacy policy, please visit http://www.google.com. We also may use other analytic means to evaluate the use of our Website and Services and for analysis and statistical purposes. We use these tools to help us improve our Services, performance and user experiences.</p>
                   < p style={{paddingTop: '660px',}}><b>Do Not Track</b></p>
                   < p style={{paddingTop: '690px',}}>Some web browsers may let you enable a "do not track" feature that sends signals to the websites you visit, indicating that you do not want your online activities tracked. This is different than blocking or deleting cookies, as browsers with a "do not track" feature enabled may still accept cookies. There is currently no industry standard for how companies should respond to "do not track" signals, although one may develop in the future. We do not respond to "do not track" requests or signals at this time. If we do so in the future, we will describe how in this Policy.</p>
        </div> 
        <div className="p5" style={{ height: '140vh',}} >
                  < h2 style={{paddingTop: '0px',}}>5. How You Can Access and Modify Your Personal Information</h2>
                  < p style={{paddingTop: '40px',}}>Where permitted by law, Microsemi will take reasonable steps to permit you to access and modify Personal Information that you have submitted by logging into your account and updating your profile but we reserve the right to use Personal Information obtained or provided previously to verify your identity or take other actions that we believe are appropriate. You can also exercise your rights of access and request corrections, suppression or deactivation of your Personal Information under applicable data protection laws by contacting us directly at the email address provided below. We make good faith efforts to honor reasonable requests to access, delete, update, suppress, or correct your data. We will respond to your request within 30 days. If we are unable to honor your request, we will provide you with an explanation. Please note that copies of information that you have updated, modified or deleted may remain viewable in cached and archived pages of the Website for a period of time.</p>
                  < h2 style={{paddingTop: '380px',}}>6. How You Can Manage Your Communication Preferences</h2>
                  < p style={{paddingTop: '420px',}}>We may send periodic promotional or informational emails to you about our products, services or our Website. You can manage your communication preference by following the instructions included in each promotional email from us to either continue to subscribe to or unsubscribe from that particular mailing or by clicking on the "Stay Informed" on the bottom of our Website page and follow instructions. If you chose to unsubscribe to promotional or informational emails on a particular matter, we may still send you emails about your account, on any services you have requested or received from us or other required communications in connection with our products and services. You can also indicate your preferences for communication notifications, such as product changes or updated literature, or offers are only available electronically in your account setting on our Website. Please note that even if you choose not to receive electronic communications from us, our terms and conditions and policies, such as Website Terms of Use, Privacy Policy, and Terms and Condition will still govern your use of our Website any products you purchase or samples you request.</p>
         </div> 
        <div className="p6" style={{ height: '80vh',}} >
                  < h2 style={{paddingTop: '0px',}}>7. How We Secure Your Information</h2>
                   < p style={{paddingTop: '40px',}}>We intend to protect the personal information entrusted to us and treat it securely in accordance with this Privacy Statement. We implement physical, administrative and technical safeguards to protect your Personal Information from misuse, and unauthorized access, disclosure, alteration and destruction. However, please be aware that despite our efforts, the internet cannot be guaranteed to be 100% secure or error-free and we cannot ensure or warrant the security of any Personal Information you provide to us. It is your responsibility to protect against unauthorized access to your user ID, password, phone number, and computer by, among other things, signing off after using a shared computer, choosing a robust password that nobody else knows or can easily guess, and keeping your user ID and password private. You must notify Microsemi immediately at if you suspect that your password or user ID has been compromised. You are solely responsible for any unauthorized use of the Website conducted via your password and user ID. We are not responsible for any lost, stolen, or compromised passwords or for any activity on your account via unauthorized password activity.</p>
        </div> 
        <div className="p7" style={{ height: '100vh',}} >
                   < h2 style={{paddingTop: '0px',}}>8. Your Consent to Transfer and Storing of Data</h2>
                   < p style={{paddingTop: '40px',}}>We keep data in California and also have servers, employees, and contractors around the United States of America and around the world in various locations. As Microsemi is a global organization, we may transfer your Personal Information to Microsemi in the United States or to any Microsemi subsidiaries and affiliates worldwide or to third parties and business partners that located in various countries around the world. By using our Website or providing any Personal Information to us, you fully understand and consent to the transfer, processing, and storage of such information outside of your country of residence where data protection standards may be different. We will retain and use your Personal Information as needed to fulfill the purpose for which it was collected. We will retain and use Personal Information as necessary to comply with our business requirements, legal obligations, resolve disputes or enforce our agreements. Subject to any applicable business, legal, or regulatory requirements, we delete or erase Personal Information when it is no longer required to enforce our rights or meet our obligations.</p>
                   < h2 style={{paddingTop: '400px',}}>9. Children's Privacy</h2>
                   < p style={{paddingTop: '440px',}}>Our Website and Services are intended for adults. We do not intentionally or knowingly accept, collect, use or disclose personal informati from anyone under the age of 13 and we request that individuals under the age of 13 not submit any personal information on the Website.</p>
        </div> 
        <div className="p8" style={{ height: '110vh',}} >
                    < h2 style={{paddingTop: '0px',}}>10. Link to Third-Party Sites</h2>
                   < p style={{paddingTop: '40px',}}>Our Website and Services may contain links to third party websites or automatically produce search results that refer or link to other party websites. Microsemi is providing these links to you only as a convenience and the inclusion of any of these links does not constitute any endorsement by Enviropromise pvt ltd Links to other websites are not under the control of Microsemi and Microsemi is not responsible for the content or the accuracy or reliability of any such contents and materials made on any linked site or any link contained in a linked site, or any changes or updates to such sites. Any access to and use of such linked sites is not governed by this Policy, but instead is governed by the privacy policies of those third-party websites. We are not responsible for the information and privacy practices of such third party websites. Third parties may independently collect information about their website visitors. We cannot control the collection of this information. Your use of third-party websites is at your own risk.</p> 
                   < h2 style={{paddingTop: '400px',}}>11. Effective Data, Policy Change</h2>
                   < p style={{paddingTop: '440px',}}>This Policy is current as of the Effective Date set forth above. We reserve the right to change, modify, add or remove portions of this Policy at any time and in our sole discretion. If we decide to change our Policy, we will post those changes on this page. When you visit the Website, you are accepting the current version of this Policy as posted on the Website at that time. We recommend that users revisit this Policy on occasion to learn of any changes.</p>      
        </div> 
        <div className="p9" style={{ height: '140vh',}} >
                   < h2 style={{paddingTop: '0px',}}>12. How You Can Contact Us</h2>
                   < p style={{paddingTop: '40px',}}>Please feel free to contact us with any comments or questions you might have regarding the information practices described in this Policy. You can contact us via our social media.</p>
                   < h2 style={{paddingTop: '160px',}}>13. Communicating With You</h2>
                   < p style={{paddingTop: '200px',}}>By using our Website and products and services or otherwise providing Personal information to us, you agree that we may communicate with you electronically regarding security, privacy, and administrative issues relating to your use. For example, if we learn of a security system's breach, we may attempt to notify you electronically by posting a notice on our Website, by sending an email, or otherwise contacting you.</p>
                   < h2 style={{paddingTop: '360px',}}>14. Law and jurisdiction</h2>
                   < p style={{paddingTop: '400px',}}>By visiting the Website, or using any of our Services, you agree that your Personal Information will be handled as described in this Policy. Your use of our Website or Services and any dispute over privacy, are subject to this Policy and our Website Terms of Use, including its applicable limitations on damages and the resolution of disputes. Enviropromise Pvt ltd Terms of Use are incorporated by reference into this Policy. Policy Policy, we how we collect, use, disclose information, Personal Information obtain about visitors websites and the service available through our ("Services"). "Personal Information" means any information or set of information that could to identify or contact individual, such as the individual's name, titl mailing address, email phone number, employer/profession, lo information, password, card information or othe specific types of person information.</p>
        </div>                   
 </div>
);
};

export default Privacy;